services:
  - type: web
    name: hosla-public-chatbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    runtime: python-3.11.4
    branch: main
    region: oregon
    repo: https://github.com/Sreejita67/Hosla_Public_ChatBot
